apiVersion: camunda.crossplane.io/v1alpha1
kind: Cluster
metadata:
  name: my-camunda-cluster-123
spec:
  forProvider:
    channel: 6bdf0d1c-3d5a-4df6-8d03-762682964d85
    generation: "d54fde93-275f-480d-a7b4-bc52435a447a"
    planType: "231932af-0223-4b60-9961-fe4f71800760" # Trial Package
    region: "2f6470f9-77ec-4be5-9cdc-3231caf683ec"  # Europe West
  writeConnectionSecretToRef:
    name: my-cluster-details
    namespace: default
  providerConfigRef:
    name: example