apiVersion: camunda.crossplane.io/v1alpha1
kind: Cluster
metadata:
  name: my-camunda-cluster-123
spec:
  forProvider:
    channel: 6bdf0d1c-3d5a-4df6-8d03-762682964d85
    generation: 9a91e023-a3c0-4949-90c5-809ff06a4dfc # Zeebe 8.2.2
    planType: 37b564b6-3ce8-4f98-a64e-96a64b38d06b # Trial Package
    region: 67836c51-4b5a-462c-91ca-fcccd792007f  # Europe West
  writeConnectionSecretToRef:
    name: my-cluster-details
    namespace: default
  providerConfigRef:
    name: example
